export const shoes = [
  {
    id: 1,
    name: 'Nike Air Max',
    price: '₹6,499',
    catagery: 'nike',
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQLLlRzu7jLfCXj-u-eaCWN84vnPVa4VlNMkOVkXWAaXts4Idtp2ojke9wEYPuVkofJIxA1Yw4Sv-HcGiryZVIE2FPzFLD9Sk8JTC4Ey9CiMnlZzuiMKWJYvRU',
  },
  {
    id: 2,
    name: 'Adidas Ultra Boost',
    price: '₹7,999',
    catagery: 'adidas',
    image: 'https://static.nike.com/a/images/f_auto/dpr_3.0,cs_srgb/h_363,c_limit/efc73ba2-d7c2-4761-9f92-bc5d50f263f4/step-into-the-future-with-the-nike-air-max-muse.png',
  },
  {
    id: 3,
    name: 'Puma Rider',
    price: '₹5,299',
    catagery: 'puma',
    image: 'https://www.asphaltgold.com/cdn/shop/files/vz4TMb2KIaFcxSVYaIqA_DH8010-108-Nike-Wmns-Air-Max-90-White-Wolf-Grey-Photon-Dust-Black-SM-1.jpg?crop=center&height=768&v=1735565085&width=768',
  },
  {
    id: 4,
    name: 'air jordan',
    price: '₹6,499',
    catagery: 'nike',
    image: 'https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/4bf92bd1-7d40-466b-9629-9fb36ce988c6/AIR+JORDAN+1+MID+%28GS%29.png',
  },
  {
    id: 5,
    name: 'Adidas casual',
    price: '₹7,999',
    catagery: 'adidas',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkf44-vMWBlcgPjDiQ76Ex4xYqqvbHfFuUnA&s',
  },
  {
    id: 6,
    name: 'Puma snikers',
    price: '₹5,299',
    catagery: 'puma',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsausIuqOk1abp6FunB7Gwyho4UzwwS5uG7g&s',
  },
  {
    id: 7,
    name: 'Nike casual',
    price: '₹6,499',
    catagery: 'nike',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMEBCv8qA9XI9ZV1XsXnRZRFSk8xWRy2YfzQ&s',
  },
  {
    id: 8,
    name: 'Adidas red',
    price: '₹7,999',
    catagery: 'adidas',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnx8ouKtUc4i0yV_CNqgOkDyRaGZUaHc1ftg&s',
  },
  {
    id: 9,
    name: 'Puma gstatic',
    price: '₹5,299',
    catagery: 'puma',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWTRQrnlXe5DQ8LD23KIaON1PRu2GlmHrjqA&s',
  },
];